# Generated by Django 4.1.3 on 2022-11-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0010_post_created_by_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
    ]
